[build]
command = "npm run build"
functions = './functions'
publish = "./dist/project-arapov/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/404"
  function = "404"